handle error

diff --git a/src/jobs/release.yml b/src/jobs/release.yml
--- a/src/jobs/release.yml
+++ b/src/jobs/release.yml
@@ -45,8 +45,9 @@ steps:
         if [ -n "$sbom_file" ]; then
           git add "$sbom_file"
           git commit -m "chore(sbom): add $sbom_file [skip ci]" || echo "No changes to commit"
-          git push origin ${CIRCLE_BRANCH}
+          git push origin ${CIRCLE_BRANCH} || echo "Git push failed"
         fi
+        rm -rf tmp/ml-depcheck-utility
       elif ls | grep -Eq '^sbom-yarn-v[0-9]+\.[0-9]+\.[0-9]+\.csv$'; then
         echo "Found SBOM, running YARN SBOM script"
         git clone https://github.com/mojaloop/ml-depcheck-utility.git ./tmp/ml-depcheck-utility
@@ -59,8 +60,9 @@ steps:
         if [ -n "$sbom_file" ]; then
           git add "$sbom_file"
           git commit -m "chore(sbom): add $sbom_file [skip ci]" || echo "No changes to commit"
-          git push origin ${CIRCLE_BRANCH}
+          git push origin ${CIRCLE_BRANCH} || echo "Git push failed"
         fi
+        rm -rf tmp/ml-depcheck-utility
       else
         echo "No SBOM CSV file found"
       fi
